import Foundation

// Keeps the locally-installed coturn (via `brew install coturn`) in sync with
// this agent's randomly-generated TURN secret and the machine's current
// public/private IP — no more manually editing turnserver.conf or copying a
// secret out of the log. Assumes coturn was installed once via Homebrew and
// is managed by `brew services`; this only rewrites its config and restarts
// it when something actually changed (not on every launch).
//
// This does NOT bundle/install coturn itself — that's a separate, bigger step
// only needed if this agent is ever distributed to machines that don't have
// Homebrew coturn already set up.
actor TurnServerManager {
    static let shared = TurnServerManager()

    private static let confPath = "/opt/homebrew/etc/turnserver.conf"
    private static let port = 7788          // shares the WS port number (UDP only, see no-tcp below)
    private static let relayMinPort = 49160
    private static let relayMaxPort = 49260

    private var lastWrittenContent: String?

    /// Call once at startup and again whenever the resolved public IP changes.
    func sync(publicIP: String?) async {
        guard let publicIP, !publicIP.isEmpty else { return }
        let secret = TurnCredentials.ensureSecret()
        let privateIP = Self.primaryPrivateIP()
        let content = Self.renderConf(secret: secret, publicIP: publicIP, privateIP: privateIP)

        guard content != lastWrittenContent else { return } // nothing changed, skip restart
        guard (try? content.write(toFile: Self.confPath, atomically: true, encoding: .utf8)) != nil else {
            ConnectionLogger.shared.logStep(sessionId: "turn", step: "conf_write_failed",
                detail: "path=\(Self.confPath)")
            return
        }
        lastWrittenContent = content
        ConnectionLogger.shared.logStep(sessionId: "turn", step: "conf_written",
            detail: "public=\(publicIP) private=\(privateIP ?? "?")")
        await restartCoturn()
    }

    private func restartCoturn() async {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/opt/homebrew/bin/brew")
        task.arguments = ["services", "restart", "coturn"]
        let pipe = Pipe()
        task.standardOutput = pipe
        task.standardError = pipe
        do {
            try task.run()
            task.waitUntilExit()
            let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
            ConnectionLogger.shared.logStep(sessionId: "turn", step: "coturn_restarted",
                detail: "exit=\(task.terminationStatus) \(out.trimmingCharacters(in: .whitespacesAndNewlines))")
        } catch {
            // Not fatal — coturn just keeps running with whatever config it last
            // loaded (or isn't installed at all, in which case TURN is simply
            // unavailable and WebRTC falls back to STUN/direct/WebSocket).
            ConnectionLogger.shared.logStep(sessionId: "turn", step: "coturn_restart_failed",
                detail: "\(error)")
        }
    }

    // A "connect a UDP socket and read back the source address" trick sounds
    // robust but isn't: system-wide VPN/proxy tools (Surge, etc.) intercept
    // that connect() too and hand back their own virtual-interface address
    // (seen on this dev machine: 198.18.0.1, a Surge TUN gateway, instead of
    // the real LAN IP). Enumerating real hardware interfaces directly — only
    // "en*" names, which is what Wi-Fi/Ethernet use on macOS — sidesteps that
    // since virtual adapters are utun*/ipsec*/bridge*/etc.
    private static func primaryPrivateIP() -> String? {
        getIfaceAddresses().first { $0.ifname.hasPrefix("en") }?.ip
    }

    private static func renderConf(secret: String, publicIP: String, privateIP: String?) -> String {
        let isIPv6 = publicIP.contains(":")
        // NAT mapping only makes sense for IPv4 behind a router; an IPv6
        // address is normally bound directly to the interface already.
        let externalIPLine = (!isIPv6 && privateIP != nil)
            ? "external-ip=\(publicIP)/\(privateIP!)\n" : ""

        return """
        # Auto-generated by RemoterAgent (TurnServerManager.swift) — do not edit by
        # hand, it gets overwritten on every startup / IP change.
        listening-port=\(port)
        no-tcp
        min-port=\(relayMinPort)
        max-port=\(relayMaxPort)
        \(externalIPLine)use-auth-secret
        static-auth-secret=\(secret)
        realm=remoter.local
        no-cli
        no-loopback-peers
        no-multicast-peers
        denied-peer-ip=10.0.0.0-10.255.255.255
        denied-peer-ip=172.16.0.0-172.31.255.255
        denied-peer-ip=192.168.0.0-192.168.255.255
        denied-peer-ip=127.0.0.0-127.255.255.255
        fingerprint
        stale-nonce=600
        log-file=/opt/homebrew/var/log/turnserver.log
        no-stdout-log
        """
    }
}
